version: '3.8'

services:
  pdf2exam:
    image: trucxinhlunglinh/sign-language:2.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./videos:/app/videos
    networks:
      - sign-language

networks:
  sign-language:
    driver: bridge
